### ISSUE TITLE
RSA private key made public

### ISSUE THREAD

**Issue by irfansharif** [ridwanmsharif/cache#1]
Introduced in https://github.com/ridwanmsharif/cache/commit/a7dd2ff9eb507a58b1a465658446b25a7ee51058`, _literally_ starts with `BEGIN RSA PRIVATE KEY`. Will be hacking you now for future lesson.

**Comment by ridwanmsharif** [comment]
The one k-v pair now made secure. Thanks for creating the issue @irfansharif. Good work
