### ISSUE TITLE
What are "Acconuts" and where can I get some

### ISSUE THREAD

**Issue by irfansharif** [ridwanmsharif/cache#2]
https://github.com/ridwanmsharif/cache/blob/9bd407f21a72ffc55803216145fd2dbce43429e7/idl/app.proto#L39

**Comment by ridwanmsharif** [comment]
IDL updated. Good catch. Must have a lot of time in your hands.

**Comment by irfansharif** [comment]
![giphy](https://user-images.githubusercontent.com/10536690/29255170-90f62938-806c-11e7-9e2c-1195c0e967e1.gif)

**Comment by ridwanmsharif** [comment]
This isn't facebook. Go away
